config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("reservations/", include("reservations.urls", namespace="reservations")),
    path("reviews/", include("reviews.urls", namespace="reviews")),
    path("lists/", include("lists.urls", namespace="lists")),
    path("conversations/", include("conversations.urls", namespace="conversations")),
    path("admin/", admin.site.urls)
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

# urlpatterns 에 들어가는 값은 class 일 수 없음
# as_view()로 function 의 형식으로 집어넣어야 함
urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home")
]

lists/urls.py
from django.urls import path
from . import views


app_name = "lists"

urlpatterns = [
    path("toggle/<int:room_pk>", views.toggle_room, name="toggle-room"),
    path("favs/", views.SeeFavsView.as_view(), name="see-favs"),
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("create/", views.CreateRoomView.as_view(), name="create"),
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("<int:pk>/edit/", views.EditRoomView.as_view(), name="edit"),
    path("<int:pk>/photos/", views.RoomPhotosView.as_view(), name="photos"),
    path("<int:pk>/photos/add/", views.AddPhotoView.as_view(), name="add-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/delete/",
         views.delete_photo,
         name="delete-photo"),
    path("<int:room_pk>/photos/<int:photo_pk>/edit/",
         views.EditPhotoView.as_view(),
         name="edit-photo"),
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/forms.py
from django import forms
from django_countries.fields import CountryField
from . import models


class SearchForm(forms.Form):

    # models 처럼 사용하는데 forms. 으로 시작하면 됨
    # widgets 을 통해 표시되는 형식을 바꿀 수 있음 (widgets=forms.Textarea)
    city = forms.CharField(initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False,
        empty_label="Any kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    # help text 를 모델에 붙이면 admin 에 help text 로 보이고 form 에 붙이면 form 화면에 나옴
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple()
    )
    facilities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple()
    )


class CreatePhotoForm(forms.ModelForm):
    class Meta:
        model = models.Photo
        fields = ("caption", "file")

    def save(self, pk, *args, **kwargs):
        photo = super().save(commit=False)
        room = models.Room.objects.get(pk=pk)
        photo.room = room
        photo.save()


class CreateRoomForm(forms.ModelForm):
    class Meta:
        model = models.Room
        fields = (
            "name",
            "description",
            "country",
            "city",
            "price",
            "address",
            "guests",
            "beds",
            "bedrooms",
            "baths",
            "check_in",
            "check_out",
            "instant_book",
            "room_type",
            "amenities",
            "facilities",
            "house_rules",
        )

    def save(self, *args, **kwargs):
        room = super().save(commit=False)
        return room

rooms/views.py
# from datetime import datetime
# from math import ceil
# from django.shortcuts import render, redirect
# from django.http import HttpResponse
# from django.core.paginator import Paginator, EmptyPage
# from . import models

from django.utils import timezone
from django.http import Http404
from django.views.generic import ListView, DetailView, View, UpdateView, FormView
from django.urls import reverse
from django.shortcuts import render, redirect, reverse
from django.core.paginator import Paginator
from django_countries import countries
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from users import mixins as user_mixins
from . import models, forms


# def all_rooms(request):
#     # print(dir(request.GET))
#     # print(request.GET.get("page", 0))
#
#     # 이건 dictionary 기능 호출한 것, or 1 은 page 를 잘못 입력해도 최소 1을 보장하려고
#     page = int(request.GET.get("page", 1) or 1)
#     page_size = 10
#     limit = page_size * page
#     offset = limit - page_size
#     # django 는 lazy 해서 all() 싫행한 다음이 아닌 limit 까지 본 다음에 실행함
#     all_rooms_list = models.Room.objects.all()[offset:limit]
#     page_count = ceil(models.Room.objects.count() / page_size)
#
#     # template 코드에서는 파이썬의 모든 기능을 지원하지 않으므로 아예 여기서 만들어서 넘김
#     return render(request, "rooms/room_list.html",
#                   context={"rooms": all_rooms_list,
#                            "page": page,
#                            "page_count": page_count,
#                            "page_range": range(1, page_count + 1),
#                            })


# Paginator 를 이용하면 페이지 넘기는 기능을 엄청 간단하게 만들 수 있음
# def all_rooms(request):
#     page = request.GET.get("page", 1)
#     # queryset 은 lazy 하므로 밑에처럼 하는 것은 틀만 만들고 데이터를 실제로 불러오지 않음
#     # 따라서 부하주지 않음 print() 이런 것 하기 전까지는
#     room_list = models.Room.objects.all()
#     # orphans 로 원래 페이지 크기인 10개보다 작을 때 orphans 수 이하의 갯수를 숨김 (페이지에 몇 개만 남는 것 방지, 그 전 페이지에 합쳐버림)
#     paginator = Paginator(room_list, 10, orphans=5)
#
#     try:
#         # get_page 는 좀 더 사용하기 편하게 많은 처리를 해줬고 page 는 각각 에러 상황을 지정해야 되지만 자유도가 높음
#         rooms = paginator.page(int(page))
#         return render(request, "rooms/room_list.html", {"page": rooms})
#     except EmptyPage:
#         # redirect 를 하면 url 에 user가 page=2332339 이렇게 쳐도 / 로 다시 돌아가므로 깔끔
#         return redirect("/")


# ListView 만으로 모델을 지정해주고 template html 을 원하는 방식 (room_list) 로 지정해주면 작동
# class 가 동작하는 동안 사용할 수 있는 object_list 가 있고 이를 통해 page.object_list 할 필요도 없이 바로 활용 가능
# 너무 추상화가 많이 되어 있어 function based view 만을 써야 된다는 식의 논쟁이 있음
# class based view 는 정해진 일을 수행하는데 정말 좋음. 다만, 커스터마이즈된 기능을 쓰고 싶다면 function based view 가 좋음
class HomeView(ListView):

    """ HomeView Definition """

    model = models.Room
    paginate_by = 12
    paginate_orphans = 5
    ordering = "created"

    context_object_name = "rooms"

    # html 에서는 page_obj 로 이미 정의된 page 객체를 바탕으로 화면을 구성할 수 있음

    # ListView 클래스에 정의된 객체 외에 추가적인 객체를 정의해서 template 에서 활용 가능
    # def get_context_data(self, **kwargs):
    #     # 여기서 상속을 받아야 ListView 에서 정의된 모든 객체들을 쓸 수 있음
    #     context = super().get_context_data(**kwargs)
    #     now = timezone.now()
    #     context["now"] = now
    #     return context


# 짧고 paginate 할 것도 없어 그냥 이렇게 function based view 로 써도 됨
# def room_detail(request, pk):
#     try:
#         room = models.Room.objects.get(pk=pk)
#         return render(request, "rooms/room_detail.html", {"room": room})
#     except models.Room.DoesNotExist:
#         # debug = False 해야 페이지 나옴
#         raise Http404()


class RoomDetail(DetailView):

    """ RoomDetail Definition """

    model = models.Room


# django form API 를 이용하지 않는 방식
# def search(request):
#     city = request.GET.get("city", "anywhere")
#     city = str.capitalize(city)
#     country = request.GET.get("country", "KR")
#     room_type = int(request.GET.get("room_type", 0))
#     price = int(request.GET.get("price", 0))
#     guests = int(request.GET.get("guests", 0))
#     bedrooms = int(request.GET.get("bedrooms", 0))
#     beds = int(request.GET.get("beds", 0))
#     baths = int(request.GET.get("baths", 0))
#     instant = bool(request.GET.get("instant", False))
#     superhost = bool(request.GET.get("superhost", False))
#     s_amenities = request.GET.getlist("amenities")
#     s_facilities = request.GET.getlist("facilities")
#
#     # 입력할 것
#     form = {
#         "city": city,
#         "s_country": country,
#         "s_room_type": room_type,
#         "price": price,
#         "guests": guests,
#         "bedrooms": bedrooms,
#         "beds": beds,
#         "baths": baths,
#         "instant": instant,
#         "superhost": superhost,
#         "s_amenities": s_amenities,
#         "s_facilities": s_facilities,
#     }
#
#     room_types = models.RoomType.objects.all()
#     amenities = models.Amenity.objects.all()
#     facilities = models.Facility.objects.all()
#
#     # db 에서 나오는 것
#     choices = {
#         "countries": countries,
#         "room_types": room_types,
#         "amenities": amenities,
#         "facilities": facilities,
#     }
#
#     filter_args = {}
#
#     if city != "Anywhere":
#         filter_args["city__startswith"] = city
#
#     filter_args["country"] = country
#
#     if room_type != 0:
#         # foreign key 이므로 pk 로 접근
#         filter_args["room_type__pk"] = room_type
#
#     if price != 0:
#         filter_args["price_lte"] = price
#
#     if guests != 0:
#         filter_args["guests_gte"] = guests
#
#     if bedrooms != 0:
#         filter_args["bedrooms_gte"] = bedrooms
#
#     if beds != 0:
#         filter_args["beds_gte"] = beds
#
#     if baths != 0:
#         filter_args["baths_gte"] = baths
#
#     if instant is True:
#         filter_args["instant_book"] = True
#
#     if superhost is True:
#         filter_args["host__superhost"] = True
#
#     if len(s_amenities) > 0:
#         for s_amenity in s_amenities:
#             filter_args["amenities__pk"] = int(s_amenity)
#
#     if len(s_facilities) > 0:
#         for s_facility in s_facilities:
#             filter_args["facilities__pk"] = int(s_facility)
#
#     rooms = models.Room.objects.filter(**filter_args)
#
#     return render(request,
#                   "rooms/search.html",
#                   {**form, **choices, "rooms": rooms}
#                   )

class SearchView(View):
    def get(self, request):
        # request.GET 을 인자로 주면 값을 기억함 + bounded 된 데이터를 바탕으로 validation 을 진행
        # form = forms.SearchForm(request.GET)

        country = request.GET.get("country")

        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bathrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilities = form.cleaned_data.get("facilities")

                filter_args = {}

                if city != "Anywhere":
                    filter_args["city__startswith"] = city

                filter_args["country"] = country

                if room_type is not None:
                    filter_args["room_type"] = room_type

                if price is not None:
                    filter_args["price_lte"] = price

                if guests is not None:
                    filter_args["guests_gte"] = guests

                if bedrooms is not None:
                    filter_args["bedrooms_gte"] = bedrooms

                if beds is not None:
                    filter_args["beds_gte"] = beds

                if baths is not None:
                    filter_args["baths_gte"] = baths

                if instant_book is True:
                    filter_args["instant_book"] = True

                if superhost is True:
                    filter_args["host__superhost"] = True

                # cleaned_data 에서는 전부 queryset 으로 정리되어 있으므로 pk 같은 식으로 접근할 필요 없이 이렇게 활용
                for amenity in amenities:
                    filter_args["amenities"] = int(amenity)

                for facility in facilities:
                    filter_args["facilities"] = int(facility)

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)

                page = request.GET.get("page", 1)

                rooms = paginator.get_page(page)

                return render(request,
                              "rooms/search.html",
                              {"form": form, "rooms": rooms})
        else:
            form = forms.SearchForm()

        # url 을 사용자가 이상하게 조작할 수도 있기 때문에 여기에 항상 return 하게 넣어줌 (에러라도 보여줌)
        return render(request,
                      "rooms/search.html",
                      {"form": form})


class EditRoomView(user_mixins.LoggedInOnlyView, UpdateView):
    model = models.Room
    template_name = "rooms/room_edit.html"
    fields = (
        "name",
        "description",
        "country",
        "city",
        "price",
        "address",
        "guests",
        "beds",
        "bedrooms",
        "baths",
        "check_in",
        "check_out",
        "instant_book",
        "room_type",
        "amenities",
        "facilities",
        "house_rules",
    )

    def get_object(self, queryset=None):
        room = super().get_object(queryset=queryset)
        if room.host.pk != self.request.user.pk:
            raise Http404
        return room


class RoomPhotosView(user_mixins.LoggedInOnlyView, DetailView):

templates/rooms/detail.html
{% extends "base.html" %}

{% block page_name %}
    Home
{% endblock page_name %}

{% block content %}
<div>
    <h1>{{ room.name }}</h1>
    <h3>{{ room.description }}</h3>
</div>
<div>
    <h2>By: {{ room.host.username }}
    {% if room.host.superhost %}
        (super host)
    {% else %}
        (general host)
    {% endif %}
    </h2>
    <h3>Amenities</h3>
    <ul>
    {% for a in room.amenities.all %}
        <li>{{ a }}</li>
    {% endfor %}
    </ul>
    <h3>Facilities</h3>
    <ul>
    {% for f in room.facilities.all %}
        <li>{{ f }}</li>
    {% endfor %}
    </ul>
    <h3>House Rules</h3>
    <ul>
    {% for hr in room.house_rules.all %}
        <li>{{ hr }}</li>
    {% endfor %}
    </ul>
</div>

{% endblock content %}

templates/rooms/photo_create.html
{% extends "base.html" %}

{% block page_title %}
    Upload photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Upload photo" %}

    </div>
{% endblock content %}

templates/rooms/photo_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update photo
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update photo" %}

    </div>
{% endblock content %}

templates/rooms/room_create.html
{% extends "base.html" %}

{% block page_title %}
    Create Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Create room" %}

    </div>
{% endblock content %}

templates/rooms/room_detail.html
{% extends "base.html" %}
{% load is_booked on_favs %}
{% load i18n %}

{% block page_title %}
    {{ room.name }}
{% endblock page_title %}

{% block content %}

    <div class="-mt-5 container max-w-full h-75vh flex mb-20">
        <div class="h-full w-1/2 bg-center bg-cover" style="background-image:url({{room.first_photo}})"></div>
        <div class="h-full w-1/2 flex flex-wrap">
            {% for photo in room.get_next_four_photos %}
                <div style="background-image:url({{photo.file.url}})" class="w-1/2 h-auto bg-cover bg-center border-gray-500 border"></div>
            {% endfor %}
        </div>
    </div>

    <div class="container mx-auto flex justify-around pb-56">
        <div class="w-1/2">
            <div class="flex justify-between">
                <div class="mb-5">
                    <h4 class="text-3xl font-medium mb-px">{{ room.name }}</h4>
                    <span class="text-gray-700 font-light">{{ room.city }}</span>
                </div>
                <a href="{{ room.host.get_absolute_url }}" class="flex flex-col items-center">
                    {% include "mixins/user_avatar_info.html" with user=room.host %}
                    <span class="mt-3 text-gray-500">{{ room.host.first_name }}</span>
                </a>
            </div>
            {% on_favs room as on_favs_boolean %}
            {% if on_favs_boolean %}
                <a class="btn-link block mb-10 w-1/3" href="{% url 'lists:toggle-room' room.pk %}?action=remove">{% trans "Remove from Favourites" %}</a>
            {% else %}
                <a class="btn-link block mb-10 w-1/3 bg-green-500" href="{% url 'lists:toggle-room' room.pk %}?action=add">{% trans "Save to Favourites" %}</a>
            {% endif %}
            <div class="flex border-section">
                <span class="mr-5 font-light">{{ room.room_type }}</span>
                <span class="mr-5 font-light">{{ room.beds }} bed{{ room.beds | pluralize }}</span>
                <span class="mr-5 font-light">{{ room.bedrooms }} bedroom{{ room.bedrooms | pluralize }}</span>
                <span class="mr-5 font-light">{{ room.baths }} bath{{ room.baths | pluralize }}</span>
                <span class="mr-5 font-light">{{ room.guests }} guest{{ room.guests | pluralize }}</span>
            </div>
            <p class="border-section">
                {{ room.description }}
            </p>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Amenities</h4>
                {% for a in room.amenities.all %}
                    <li class="mb-2">{{ a }}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">Facilities</h4>
                {% for f in room.facilities.all %}
                    <li class="mb-2">{{ f }}</li>
                {% endfor %}
            </div>
            <div class="border-section">
                <h4 class="font-medium text-lg mb-5">House Rules</h4>
                {% for hr in room.house_rules.all %}
                    <li class="mb-2">{{ hr }}</li>
                {% endfor %}
            </div>
            <div class="mt-10">
                <h4 class="font-medium text-2xl mb-5">Reviews</h4>
                <div class="flex items-center">
                    <div>
                        <i class="fas fa-star text-red-300"></i>
                        <span class="font-bold text-xl">{{ room.total_rating }}</span>
                    </div>
                    <div class="h-5 w-px bg-gray-400 mx-5"></div>
                    <div>
                        <span class="font-bold text-xl mr-1">{{ room.reviews.count }}</span>
                        <span>review{{ room.reviews.count | pluralize }}</span>
                    </div>
                </div>
                <div>
                    {% for review in room.reviews.all %}
                        <div class="border-section">
                            <div class="mb-3 flex">
                                <div>
                                    {% include "mixins/user_avatar_info.html" with user=review.user h_and_w="w-10 h-10" text="text-lg"%}
                                </div>
                                <div class="flex flex-col ml-5">
                                    <span class="font-medium">{{ review.user.first_name }}</span>
                                    <span class="text-sm text-gray-500">{{ review.created|date:'F Y' }}</span>
                                </div>
                            </div>
                            <p>{{ review.review }}</p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="w-1/3">
            {% if room.host == user %}
                <a href="{% url 'rooms:edit' room.pk %}" class="btn-link block">Edit Room</a>
            {% else %}

                {% if not request.session.is_hosting %}
                    {% for calendar in room.get_calendars %}
                    <div class="mb-20">
                        <span class="text-center font-semibold text-lg block mb-8">{{ calendar.get_month }} / {{ calendar.year }}</span>
                        <div class="cal-grid font-medium mb-4">
                            {% for day in calendar.day_names %}
                                <span>{{ day }}</span>
                            {% endfor %}
                        </div>
                        <div class="cal-grid">
                            {% for day in calendar.get_days  %}
                                {% is_booked room day as is_booked_bool %}
                                {% if day.number != 0 %}
                                    {% if day.past %}
                                        <span class="cal-number bg-gray-200 text-gray-400">{{day}}</span>
                                    {% elif is_booked_bool %}
                                        <span class="cal-number bg-gray-200 text-gray-400 line-through">{{day}}</span>
                                    {% else %}
                                        <a href="{% url 'reservations:create' room.pk day.year day.month day.number %}" class="cal-number bg-gray-200 text-gray-700 hover:bg-red-400 hover:text-white hover:font-medium">{{day}}</a>
                                    {% endif %}
                                {% else %}
                                  <span></span>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                {% endif %}
            {% endif %}
        </div>
    </div>

{% endblock content %}

templates/rooms/room_edit.html
{% extends "base.html" %}

{% block page_title %}
    Update Room
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container lg:w-5/12 md:w-1/2 xl:w-1/4 mx-auto my-10 flex flex-col items-center border p-6 border-gray-400">

        {% include 'mixins/room/room_form.html' with form=form cta="Update room" %}

        <div class="mt-5">
            <a href="{% url 'rooms:photos' room.pk %}" class="text-green-600 font-medium">Edit Photos</a>
        </div>


    </div>
{% endblock content %}

templates/rooms/room_list.html
{% extends "base.html" %}

{% load i18n %}

{% block page_title %}
    Home
{% endblock page_title %}

{% block content %}
    <div class="container mx-auto pb-10">
        <div class="-mx-40 rounded-xl mx-auto bg-gray-800 h-50vh mt-32 mb-24 bg-cover bg-center" style="background-image:url(https://images.unsplash.com/photo-1546874177-9e664107314e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80)"></div>

        <div class="flex flex-wrap -mx-40 mb-10">
            {% for room in rooms %}
                {% include "mixins/room_card.html" with room=room %}
            {% endfor %}
        </div>

        <div class="flex items-center justify-center mx-auto container">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="text-red-200">
                    <i class="fas fa-arrow-left fa-lg"></i>
                </a>
            {% endif %}

            <span class="mx-3 font-medium text-lg">
                {% blocktrans with current_page=page_obj.number total_pages=page_obj.paginator.num_pages %}Page {{ current_page }} of {{ total_pages }}{% endblocktrans %}
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="text-red-200">
                    <i class="fas fa-arrow-right fa-lg"></i>
                </a>
            {% endif %}
        </div>
    </div>

{% endblock content %}

templates/rooms/room_photos.html
{% extends "base.html" %}

{% block page_title %}
    {{room.name}}'s Photos
{% endblock page_title %}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}

    <div class="container mx-auto my-10 flex flex-col">
        <div class="my-10 w-full">
            <a href="{% url 'rooms:add-photo' room.pk %}" class="btn-link w-1/6 block">Upload Photo</a>
        </div>

        {% for photo in room.photos.all  %}
            <div class="mb-5 border p-6 border-gray-400 flex justify-between">
                <div class="flex items-start">
                    <img src="{{photo.file.url}}" class="w-32 h-32" />
                    <span class="ml-5 text-xl">{{photo.caption}}</span>
                </div>
                <div class="flex flex-col w-1/5">
                    <a class="btn-link mb-5 bg-green-600" href="{% url 'rooms:edit-photo' room.pk photo.pk %}">Edit</a>
                    <a class="btn-link bg-red-600" href="{% url 'rooms:delete-photo' room.pk photo.pk %}">Delete</a>
                </div>
            </div>
        {% endfor %}
        <div class="flex justify-center mt-5">
            <a href="{% url 'rooms:edit' room.pk %}" class="text-red-400 font-medium text-xl">Back to room</a>
        </div>

    </div>
{% endblock content %}

templates/rooms/search.html
{% extends "base.html" %}

{% block page_title %}
    Search
{% endblock page_title%}

{% block search-bar %}
{% endblock search-bar %}

{% block content %}
    <h2>Search!</h2>

    <form method="get" action="{% url "rooms:search" %}">
{#        as_p 로 어떤 방식으로 화면에 표시할 지 정의할 수 있음#}
        {{ form.as_p }}
        <button>Search</button>
    </form>

    <h3>Results</h3>

    {% for room in rooms %}
        <h3>{{ room.name }}</h3>
    {% endfor %}


{% endblock content %}